// - inventory_header (Primary Keys: company, entity_code, order_ref)
// - partner (Primary Keys: partner_code)
// - warehouse_master (Primary Keys: company, entity_code, warehouse_code)
// - wms_app_pack (Primary Keys: company, entity_code, pack_id)
// - wms_app_pick (Primary Keys: company, entity_code, pick_id)
// - wms_app_putaway (Primary Keys: company, entity_code, put_id)
// - wms_app_receive (Primary Keys: company, entity_code, rec_id)
// - wms_app_sorting (Primary Keys: company, entity_code, sort_id)
// - wms_app_stock_take (Primary Keys: company, entity_code, stock_take_id)
// - wms_app_transfer (Primary Keys: company, entity_code, transfer_id)
// - wms_commodity (Primary Keys: company, entity_code, partner_code, commodity)
// - wms_location (Primary Keys: company, warehouse_code, location_code)
// - xwms_feedback (Primary Keys: company, entity_code, user_id, user_email, feedback_id)
// - xwms_log (Primary Keys: company, entity_code, user_id, log_id)
// - xwms_organization (Primary Keys: company, entity_code)
// - xwms_signup (Primary Keys: signup_id)
// - xwms_users (Primary Keys: company, entity_code, user_id)
